# ----------------------------------------
# Created on: Wed Nov  6 17:08:12 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/pango/pango_sim_libraries/usim"
vmap  adc "D:/pango/pango_sim_libraries/adc"
vmap  ddrc "D:/pango/pango_sim_libraries/ddrc"
vmap  ddrphy "D:/pango/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "D:/pango/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "D:/pango/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "D:/pango/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "D:/pango/pango_sim_libraries/pciegen2"
vlog   "D:/pango_prj/crtl_1.08/source/Key_Debounce.v" -work work
vlog   "D:/pango_prj/logic_test/source/glitch_free.v" -work work
vlog   "D:/pango_prj/logic_test/source/sampler.v" -work work
vlog   "D:/pango_prj/logic_test/source/logic_analyzer.v" -work work
vlog   "D:/pango_prj/logic_test/ipcore/PLL_4/PLL_4.v" -work work
vlog   "D:/pango_prj/logic_test/ipcore/RAM_0/rtl/ipm_distributed_sdpram_v1_2_RAM_0.v" -work work
vlog   "D:/pango_prj/logic_test/ipcore/RAM_0/RAM_0.v" -work work
vlog   "D:/pango_prj/logic_test/source/tb_test.v" -work work

# ----------------------------------------
