# ----------------------------------------
# Created on: Sun Oct 27 22:34:57 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/usim"
vmap  adc "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/adc"
vmap  ddrc "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/ddrc"
vmap  ddrphy "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/ddrphy"
vmap  hsst_e2 "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/hsst_e2"
vmap  iolhr_dft "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/iolhr_dft"
vmap  ipal_e1 "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/ipal_e1"
vmap  pciegen2 "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/pciegen2"
vlog   "ad_da_hdmi_top_syn.vm" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/tb_hdmi.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/tb_key_debounce.v" -work work

# ----------------------------------------
