# ----------------------------------------
# Created on: Sun Oct 27 22:37:51 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/usim"
vmap  adc "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/adc"
vmap  ddrc "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/ddrc"
vmap  ddrphy "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/ddrphy"
vmap  hsst_e2 "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/hsst_e2"
vmap  iolhr_dft "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/iolhr_dft"
vmap  ipal_e1 "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/ipal_e1"
vmap  pciegen2 "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/sim_lib/pciegen2"
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/ad_da_hdmi_top.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/ad9708_sin_wave.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/grid_display.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/hdmi_test.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/iic_dri.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/ms72xx_ctl.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/ms7200_ctl.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/ms7210_ctl.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/pattern_vg.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/sync_vg.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/timing_gen_xy.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/wav_display.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/Key_Debounce.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/Key_Debounce_fix.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/rom_sin_wave/rtl/ipml_rom_v1_5_rom_sin_wave.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/rom_sin_wave/rtl/ipml_spram_v1_5_rom_sin_wave.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/rom_sin_wave/rom_sin_wave.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/pll_clock_125m/pll_clock_125m.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/pll/pll.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/pll_adda/pll_adda.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/ram1024x8/rtl/ipml_sdpram_v1_6_ram1024x8.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/ipcore/ram1024x8/ram1024x8.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/AD_DA_50H/AD9708_sawtooth_wave/ipcore/rom_sawtooth_wave/rtl/ipml_rom_v1_5_rom_sawtooth_wave.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/AD_DA_50H/AD9708_sawtooth_wave/ipcore/rom_sawtooth_wave/rtl/ipml_spram_v1_5_rom_sawtooth_wave.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/AD_DA_50H/AD9708_sawtooth_wave/ipcore/rom_sawtooth_wave/rom_sawtooth_wave.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/tb_hdmi.v" -work work
vlog   "D:/01_Learning_projects/PDS_projects/SINGAL/HDMI/source/tb_key_debounce.v" -work work

# ----------------------------------------
